web update
life-sync/website2 pull request #58
Opened 2021-01-01 19:13 UTC by yuvraajnarula

Don't accept this pr until the website is done

2021-01-02 15:59 UTC, ion05 requested changes
Website reconstruction rejected

2021-01-05 04:47 UTC, ion05 commented
@yuvraajnarula  Remove [`0b58b1f` (#58)](https://github.com/life-sync/website2/pull/58/commits/0b58b1f14054c8c1da5cc9463e225de51bc0a0df) 
And decrease the width of the light blue section

2021-01-07 06:58 UTC, ion05 requested changes

2021-01-07 06:58 UTC, ion05 commented on index.html
> +        <div class="media">
Add title over here eg. Mobile App Developer

2021-01-07 06:58 UTC, ion05 commented on index.html
> +          <div class="media-list">
Dont put social links inside a box

2021-01-07 10:46 UTC, ion05 commented
Remove comments with code in them

2021-01-07 10:48 UTC, yuvraajnarula commented
I have to work on that part of code but later so that's why it is commented

2021-01-15 18:18 UTC, ion05 commented on index.html
> +    <div class="middle">
Jo bhi hai yeh, hatade @yuvraajnarula

2021-02-01 14:18 UTC, merged